services:
  node:
    image: tugboatqa/node:10.9
    default: true
    depends: php
    commands:
      init:
        - curl -Lo contenta.tar.gz https://github.com/contentacms/contentajs/archive/master.tar.gz
        - tar -xzf contenta.tar.gz
        - mv contentajs-master contentajs
        - cd "${TUGBOAT_ROOT}/.tugboat/" && mv contentajs.yml "${TUGBOAT_ROOT}/contentajs/config/local.yml"
        - sed -i 's/TUGBOAT_PREVIEW_URL/${TUGBOAT_PREVIEW_URL}/g' "${DOCROOT}/config/local.yml"

