services:
  node:
    image: tugboatqa/node:10.9
    default: true
    depends: php
    commands:
      init:
        - curl -Lo contenta.tar.gz https://github.com/contentacms/contentajs/archive/master.tar.gz
        - tar -xzf contenta.tar.gz
        - mv contentajs-master contentajs
        - cd "${TUGBOAT_ROOT}/.tugboat/" && mv contentajs.yml "${TUGBOAT_ROOT}/contentajs/config/local.yml"

  php:
    image: tugboatqa/php:7-apache
    # Wait until the mysql service is done building
    depends: mysql
    
    commands:
      init:
        # Install opcache and mod-rewrite.
        # - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - composer create-project contentacms/contenta-jsonapi-project contenta --stability dev --no-interaction
        # The $DOCROOT variable is not available since this isn't the default service. 
        #- ln -snf "${TUGBOAT_ROOT}/contenta/web" "/var/www/html"
        - cd "${TUGBOAT_ROOT}/.tugboat/" && cp {.env,.env.local} "${TUGBOAT_ROOT}/contenta/"
        
        # Update the .env and .env.local files
        - echo -e "SITE_MAIL=${CONTENTA_EMAIL}\nACCOUNT_MAIL=${CONTENTA_EMAIL}\nSITE_NAME='${TUGBOAT_PROJECT}'" >> "${TUGBOAT_ROOT}/contenta/.env"
        - echo -e "MYSQL_PASSWORD=tugboat\nACCOUNT_PASS=tempboat" >> "${TUGBOAT_ROOT}/contenta/.env.local"
        
        #- cd "${TUGBOAT_ROOT}/contenta/" && composer run-script install:with-mysql
        
        # Make it easier to find Drush
        - ln -sf ${TUGBOAT_ROOT}/contenta/vendor/drush/drush/drush /usr/local/bin/drush
        
        # Reset the admin password so it doesn't show in standard output. 
        - drush -r "/var/www/html" user:password admin "${CONTENTA_PWD}"
        
        # Setup the necessary file permissions. 
        - chown www-data "/var/www/html/sites/default/files"
        - chmod 744 "/var/www/html/sites/default/files"

  mysql:
    image: tugboatqa/mysql:5
