services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    
    commands:
      init:
        - a2enmod headers rewrite
        - composer create-project contentacms/contenta-jsonapi-project contenta --stability dev --no-interaction
        - ln -snf "${TUGBOAT_ROOT}/contenta/web" "${DOCROOT}"
        - cd "${TUGBOAT_ROOT}/.tugboat/" && cp {.env,.env.local} "${TUGBOAT_ROOT}/contenta/"
        
        # Update the .env and .env.local files
        - echo -e "SITE_MAIL=${CONTENTA_EMAIL}\nACCOUNT_MAIL=${CONTENTA_EMAIL}\nSITE_NAME='${TUGBOAT_PROJECT}'" >> "${TUGBOAT_ROOT}/contenta/.env"
        - echo -e "MYSQL_PASSWORD=tugboat\nACCOUNT_PASS=tempboat" >> "${TUGBOAT_ROOT}/contenta/.env.local"
        
        - cd "${TUGBOAT_ROOT}/contenta/" && composer run-script install:with-mysql
        
        # Make it easier to find Drush
        - ln -sf ${TUGBOAT_ROOT}/contenta/vendor/drush/drush/drush /usr/local/bin/drush
        
        # Reset the admin password so it doesn't show in standard output. 
        - echo "Changing admin password..."
        - drush -r "${DOCROOT}" user:password admin "${CONTENTA_PWD}"
        
        # Setup the necessary file permissions. 
        - mkdir -p "${DOCROOT}/files"
        - chown www-data "${DOCROOT}/files"
        - chmod 744 "${DOCROOT}/files"
    
  mysql:
    image: tugboatqa/mysql:5
